/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DetailCountryIdImport } from './routes/detail.$countryId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DetailCountryIdRoute = DetailCountryIdImport.update({
  id: '/detail/$countryId',
  path: '/detail/$countryId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/detail/$countryId': {
      id: '/detail/$countryId'
      path: '/detail/$countryId'
      fullPath: '/detail/$countryId'
      preLoaderRoute: typeof DetailCountryIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/detail/$countryId': typeof DetailCountryIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/detail/$countryId': typeof DetailCountryIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/detail/$countryId': typeof DetailCountryIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/detail/$countryId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/detail/$countryId'
  id: '__root__' | '/' | '/detail/$countryId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DetailCountryIdRoute: typeof DetailCountryIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DetailCountryIdRoute: DetailCountryIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/detail/$countryId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/detail/$countryId": {
      "filePath": "detail.$countryId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
